[tool.poetry]
name = "bullshitgraphs"
version = "1"
description = ""
authors = [
    "Neil Schark <neil@schark.eu>"
]

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.6.2"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.5"

